---
kind: pipeline
type: docker
name: default

steps:
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh-host
      username: monster
      password:
        from_secret: ssh-password
      port: 22
      script:
        - cd docker.services/simple-transfer-host
        - git pull && docker-compose build && docker-compose up -d

  - name: Send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: bot-token
      to: 123622180